# Generated by Django 2.1.3 on 2018-11-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField(max_length=100)),
                ('water', models.IntegerField(max_length=100)),
                ('alcohol', models.IntegerField(max_length=100)),
                ('caffeine', models.IntegerField(max_length=100)),
            ],
        ),
    ]
